# Use Node.js image
FROM node:alpine

# Set working directory
WORKDIR /app

# Copy package.json for npm install
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy all frontend files
COPY . .

# Expose port 80
EXPOSE 8080

# Start simple HTTP server
CMD ["npm", "run", "dev"]