# Use Node.js image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json for npm install
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy all frontend files
COPY . .

RUN chmod u+x create-env.sh && ./create-env.sh

# Expose port 80
EXPOSE 8080

# Start simple HTTP server
CMD ["npm", "run", "dev"]