# server {
# 	listen 8080;
# 	server_name localhost;
# 	return 301 https://localhost:8443$request_uri;
# }

server {
	listen 8080 ssl;
    server_name localhost;
    
    ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;

	root /usr/share/nginx/html;
	index index.html;

	location / {
		# if file not found -> serves index.html and react handles it (SPA)
		try_files $uri $uri/ /index.html;
	}

	location /api/ {
		proxy_pass http://backend:3000;
	}
}