server {
	listen 80;
	server_name localhost;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
    server_name localhost;
    
    ssl_certificate /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;
    ssl_protocols TLSv1.2 TLSv1.3;

	root /usr/share/nginx/html;
	index index.html;

	location / {
		# if file not found -> serves index.html and react handles it (SPA)
		try_files $uri $uri/ /index.html;
	}

	location /api/ {
		proxy_pass http://backend:3000;
	}
}