export type Screen = 
  | 'main'
  | 'local'
  | 'online'
  | 'host-lobby'
  | 'join-lobby'
  | 'ready-room'
  | 'tournament'
  | 'create-tournament'
  | 'tournament-lobby'
  | 'tournament-bracket'
  | 'countdown'
  | 'searching'
  | 'game'
  | 'timeout'
  | 'error'
  | 'websocket-connecting'
  | 'websocket-closed'

export type GameMode = 
  |'none' 
  | 'singleplayer' 
  | 'multiplayer' 
  | 'online'
