export type GameMode = 
  | "none" 
  | "singleplayer" 
  | "multiplayer" 
  | "online"

export type Screen =
  | "main"
  | "local"
  | "online"
  | "searching"
  | "host-lobby"
  | "join-lobby"
  | "ready-room"
  | "countdown"
  | "game"
  | "tournament"
  | "tournament-lobby"
  | "tournament-bracket"
  | "create-tournament"
  | "game-results"
  | "timeout"
  | "error"
  | "websocket-connecting"
  | "websocket-closed"