export type Screen = 
    | 'main'
    | 'online'
    | 'local'
    | 'host-lobby'
    | 'join-lobby'
    | 'tournament'
    | 'create-tournament'
    | 'searching'
    | 'searching-private'
    | 'game'
    | 'timeout'
    | 'info-bad'
    | 'info-neutral'
    | 'info-good'

export type GameMode = 
    | 'none'
    | 'singleplayer'
    | 'multiplayer'
    | 'online'
